const tips = [
  'Eat a Balanced Diet: Include a variety of fruits, vegetables, whole grains, lean proteins, and healthy fats in your diet.',
  'Stay Hydrated: Drink plenty of water throughout the day to keep your body hydrated and maintain optimal bodily functions.',
  'Exercise Regularly: Aim for at least 150 minutes of moderate-intensity aerobic activity or 75 minutes of vigorous-intensity activity per week.',
  'Get Enough Sleep: Aim for 7-9 hours of quality sleep each night to allow your body to rest and rejuvenate.',
  'Manage Stress: Practice stress-reduction techniques such as meditation, deep breathing, yoga, or spending time in nature.',
  'Avoid Smoking and Limit Alcohol: Quit smoking and limit alcohol consumption to promote better respiratory and cardiovascular health.',
  'Practice Good Hygiene: Wash your hands frequently, cover your mouth when coughing or sneezing, and maintain good personal hygiene.',
  'Protect Your Skin: Use sunscreen when exposed to the sun, wear protective clothing, and avoid excessive sun exposure.',
  'Stay Socially Connected: Engage with friends, family, and community to strengthen your emotional health and build a support system.',
  'Schedule Regular Check-ups: Visit your healthcare provider for routine check-ups and screenings to detect any health issues early.',
  'Limit Processed Foods and Sugars: Minimize your intake of processed and sugary foods to reduce the risk of health problems.',
  'Practice Mindful Eating: Pay attention to your eating habits, savor each bite, and eat slowly to recognize when you are full.',
  'Practice mindfulness and meditation to reduce anxiety and improve mental clarity.',
  'Engage in hobbies and activities you enjoy to boost mood and reduce stress.',
  'Limit processed and high-sugar snacks; opt for healthier alternatives like fruits and nuts.',
  'Maintain good posture to prevent back and neck pain.',
  'Prioritize self-care and take time for yourself regularly.',
  'Encourage and support others in their health and wellness journey.',
  'Limit consumption of processed and fried foods for better heart health.',
  'Engage in regular social activities to strengthen social connections.',
  'Spend time outdoors and enjoy nature for improved mental well-being.',
  'Set realistic and achievable health goals to track your progress.',
]

export default tips
